services:
  app:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - GITHUB_APP_ID=${GITHUB_APP_ID}
        - APP_INSTALL_ID=${APP_INSTALL_ID}
        - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
        - PORT=${PORT}

    ports:
      - ${PORT}:${PORT}

    environment:
      - GITHUB_APP_ID:${GITHUB_APP_ID}
      - APP_INSTALL_ID:${APP_INSTALL_ID}
      - OPEN_ROUTER_API_KEY:${OPEN_ROUTER_API_KEY}
      - PORT:${PORT}
